# Generated by Django 2.1.5 on 2019-01-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
